version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Know@9999#
      MYSQL_DATABASE: tap
    ports:
      - "3307:3306"
    volumes:
      - $/home/ec2-user/OnlineShopping/Database/tapDB.sql