name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - run: ls -l
    - name: Restore dependencies
      run: cd RecruitmentApp && dotnet restore
    - name: Build
      run: cd RecruitmentApp && dotnet build --no-restore
    - name: Test
      run: cd RecruitmentApp && dotnet test --no-build --verbosity normal
